package tst

import (
	"env"
)

var Env env.Env

var atcion map[string]string = map[string]string{
	"register":        "/agbweb/client/customer/info/register",
	"infomodify":      "/agbweb/client/customer/info/modify",
	"bankmodify":      "/agbweb/client/customer/bank/modify",
	"bankquery":       "/agbweb/client/customer/bank/query",
	"sms":             "/agbweb/client/sms",
	"login":           "/agbweb/client/customer/login",
	"logout":          "/agbweb/client/customer/logout",
	"pwdmodify":       "/agbweb/client/customer/pwd/modify",
	"pwdreset":        "/agbweb/client/customer/pwd/reset",
	"balance":         "/agbweb/client/customer/account/balance",
	"accountrecord":   "/agbweb/client/customer/account/record",
	"infoquery":       "/agbweb/client/customer/info/query",
	"byrecord":        "/agbweb/client/buy/record",
	"winrecord":       "/agbweb/client/win/record",
	"period":          "/agbweb/client/lottery/period",
	"definerecord":    "/agbweb/client/buy/define/record",
	"awardrecord":     "/agbweb/client/award/record",
	"awarddetail":     "/agbweb/client/award/detail",
	"definecancel":    "/agbweb/client/buy/define/cancel",
	"buybatch":        "/agbweb/client/buy/batch",
	"definerandom":    "/agbweb/client/buy/define/random",
	"banksave":        "/agbweb/client/trans/bank/save",
	"mobilepaysave":   "/agbweb/client/trans/mobilepay/save",
	"advice":          "/agbweb/client/advice",
	"gamequery":       "/agbweb/client/game/query",
	"gameaccumulator": "/agbweb/client/game/accumulator",
	"news":            "/agbweb/client/news",
	"newshtml":        "/agbweb/client/newsHtml",
	"charge":          "/agbweb/client/customer/charge",
	"compare":         "/agbweb/client/award/compare",
	"provincequery":   "/agbweb/client/province/query",
	"eball":           "/agbweb/client/award/eball",
	"lotterytotal":    "/agbweb/client/lottery/total",
	"paperquery":      "/agbweb/client/paper/query",
	"groupbuyrecord":  "/agbweb/client/groupbuy/record",
	"groupbuydetail":  "/agbweb/client/groupbuy/detail",
	"groupbuycreate":  "/agbweb/client/groupbuy/create",
	"groupbuyquery":   "/agbweb/client/groupbuy/query",
	"groupbytotal":    "/agbweb/client/groupbuy/total",
	"groupbuyjoin":    "/agbweb/client/groupbuy/join",
	"trend":           "/agbweb/client/lottery/trend",
	"roll":            "/agbweb/client/news/roll",
	"codelist":        "/agbweb/client/bank/codelist",
	"sysparamquery":   "/agbweb/client/sysparam/query",
	"agentgamequery":  "/agbweb/client/agentgame/query",
	"logoff":          "/agbweb/client/customer/logoff",
	"qiansan":         "/agbweb/client/lottery/qiansan",
	"zonghe":          "/agbweb/client/lottery/zonghe",
	"questionsave":    "/agbweb/client/question/save",
	"questionmodify":  "/agbweb/client/question/modify",
	"pwdpay":          "/agbweb/client/customer/pwd/pay",
	"pwdemail":        "/agbweb/client/customer/pwd/email",
	"pwdquestion":     "/agbweb/client/customer/pwd/question",
	"amountquery":     "/agbweb/client/plan/amount/query",
}
